import { ApplicationCommandType, CommandInteraction } from "discord.js";
import { Command } from "../../command";
import { isHelper } from "../../functions/Misc";

export const timeshards: Command = {
  name: "timeshards",
  description: "describe what time shards are and what they do",
  type: ApplicationCommandType.ChatInput,
  run: async(interaction: CommandInteraction) => {
    if (!interaction || !interaction.isChatInputCommand()) return;

    // eslint-disable-next-line max-len
    const content: string = "Time Shards are generated by TDs. They translate to free Tickspeed upgrades.";

    await interaction.reply({ content, ephemeral: !isHelper(interaction) });
  }
};